services:

  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    depends_on:
      - postgres
      - redis
      - mailhog
    environment:
      - PYTHONPATH=src
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - python
      - /src/entrypoints/redis_eventconsumer.py

  api:
    image: allocation-image
    depends_on:
      - redis_pubsub
      - mailhog
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - API_HOST=api
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=entrypoints/flask_app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5005:80"

  postgres:
    image: postgres:18.3
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"

  redis:
    image: redis:alpine
    ports:
      - "6378:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "11025:1025"
      - "18025:8025"

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonardb
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5433/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonar-network

  sonardb:
    image: postgres:17
    container_name: sonardb
    command: -p 5433
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonardb_data:/var/lib/postgresql/data
    networks:
      - sonar-network

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonardb_data:

networks:
  sonar-network:
    name: sonar-network