services:

  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    depends_on:
      - postgres
      - redis
      - mailhog
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - python
      - /src/allocation/entrypoints/redis_eventconsumer.py

  api:
    image: allocation-image
    depends_on:
      - redis_pubsub
      - mailhog
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - API_HOST=api
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=allocation/entrypoints/flask_app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5005:80"

  postgres:
    image: postgres:18.3
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"

  redis:
    image: redis:alpine
    ports:
      - "6378:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "11025:1025"
      - "18025:8025"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.18.1
    container_name: filebeat
    user: root
    command: ["--strict.perms=false"]
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch
      - kibana

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonardb
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5433/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonar-network

  sonardb:
    image: postgres:17
    container_name: sonardb
    command: -p 5433
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonardb_data:/var/lib/postgresql/data
    networks:
      - sonar-network

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonardb_data:
  elasticsearch_data:

networks:
  sonar-network:
    name: sonar-network